@startuml
:Visitatori del sito: as a1
:Utenti Registrati: as a2
:Impiegati: as a3
:Amministratori: as a4

rectangle system{
  (programmazione film) as pf
  (account) as ac

  (biglietti) as bi
  (posti specifici) as ps
  (abbonamenti) as ab
  (cronologia prenotazioni) as cp

  (gestione sale) as ga
  (film) as fi
  (orari proiezioni) as ap
  (prenotazioni effetuate) as pe

  (gestione personale) as gp
  (controllo incassi) as ci
  (generazione di report mensili sulle vendite) as rm
}

rectangle system{
  (snack) as sn
  (bevande) as be
  (carrello) as ca

  (sconti) as sc

  (disponibilità posti) as ds
}

a1 --> pf
a1 --> ac

a2 --> bi
a2 --> ca
bi --> ps
ab --> sc
sc --> bi
a2 --> cp

a3 --> ga
a3 --> pe

a4 --> gp
a4 --> ci
a4 --> rm
a4 --> ab

@enduml