@startuml
:Proprietario: as owner
:Ospite: as guest
:Amministratore: as admin

rectangle System {
  (Configurazione sistema) as config
  (Aggiunta dispositivi) as addDevice
  (Definizione regole) as defineRules
  (Monitoraggio consumi) as monitorEnergy
  (Controllo dispositivi) as controllo
  (Impostazione scene) as setScene
  (Aggiornamento software) as update
  (Risoluzione problemi) as solve
  (Monitoraggio sistema) as monitorSystem
  (Verifica conflitti) as checkConflict
}

owner --> config
owner --> addDevice
owner --> defineRules
owner --> monitorEnergy

guest --> controllo
guest --> setScene

admin --> update
admin --> solve
admin --> monitorSystem

defineRules --> checkConflict
@enduml